version: '3.1'

services:
    php:
        build: docker/php
        volumes:
            - ./:/var/www
        environment:
          MYSQL_DATABASE: dailymotion
          MYSQL_USER: dailymotion
          MYSQL_PASSWORD: dailymotion

    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/api.conf:/etc/nginx/conf.d/api.conf
            - ./:/var/www
        ports:
            - "80:80"
        depends_on:
            - php

    composer:
        image: composer
        volumes:
            - "./:/app"
        command: install

    mysql:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dailymotion
            MYSQL_USER: dailymotion
            MYSQL_PASSWORD: dailymotion
        volumes:
            - ./docker/mysql/initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
        ports:
            - "3306:3306"
